version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-playground
    container_name: react-playground
    ports:
      - 8080:8080
    networks:
      - appnet

networks:
  appnet:
    driver: 'bridge'