version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-express
    container_name: react-express
    ports:
      - 8080:8080
    networks:
      - appnet

networks:
  appnet:
    driver: 'bridge'