version: '3.1'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: react-express
#    container_name: react-express
#    environment:
#      - DB_PASSWORD=${DB_PASSWORD:-testPass}
#      - DB_USER=${DB_USER:-testName}
#      - DB_NAME=${DB_NAME:-testDb}
#      - DB_HOST=${DB_HOST:-localhost}
#    ports:
#      - 8080:8080
#    networks:
#      - appnet
#
#  pgadmin:
#    links:
#      - postgres:postgres
#    image: fenglc/pgadmin4
#    ports:
#      - "5050:5050"
#    networks:
#      - appnet
#    restart: unless-stopped

  postgres:
    image: circleci/postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-testPass}
      - POSTGRES_USER=${DB_USER:-testName}
      - POSTGRES_DB=${DB_NAME:-testDb}
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: 'bridge'